name: petmate

type: 'nodejs:18'

build:
    flavor: none

mounts:
  'web/uploads':
    source: local
    source_path: uploads
    
disk: 2048

hooks:
    build: |
        corepack yarn install   
        yarn build        

web:
  commands: 
    start: "node build/server.js"
         