steps:
  # Install node.js dependencies
  - name: node
    entrypoint: npm
    args: ["install"]
  # Run create-env script
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'APP_KEY=${_APP_KEY}'
      - 'DB_CONNECTION=${_DB_CONNECTION}'
      - 'DRIVE_DISK=${_DRIVE_DISK}'
      - 'FACEBOOK_CLIENT_ID=${_FACEBOOK_CLIENT_ID}'
      - 'FACEBOOK_CLIENT_SECRET=${_FACEBOOK_CLIENT_SECRET}'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
      - 'HOST=${_HOST}'
      - 'MYSQL_DB_NAME=${_MYSQL_DB_NAME}'
      - 'MYSQL_HOST=${_MYSQL_HOST}'
      - 'MYSQL_PORT=${_MYSQL_PORT}'
      - 'MYSQL_USER=${_MYSQL_USER}'
      - 'NODE_ENV=${_NODE_ENV}'
      - 'PORT=${_PORT}'
  # Run build script
  - name: node
    entrypoint: node
    args: ["ace", "build", "--production"]
  # Copy app.yaml into build folder
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "app.yaml", "build/app.yaml"]
  # Deploy application
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "build"
    args: ["app", "deploy"]
timeout: "1600s"
