# This is a basic workflow to help you get started with Actions

name: Staging CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: node
        run: |
          yarn install

      - name: Create and populate .env file
        env:
          APP_KEY: ${{secrets.APP_KEY}}
          DB_CONNECTION: ${{secrets.DB_CONNECTION}}
          DRIVE_DISK: ${{secrets.DRIVE_DISK}}
          FACEBOOK_CLIENT_ID: ${{secrets.FACEBOOK_CLIENT_ID}}
          FACEBOOK_CLIENT_SECRET: ${{secrets.FACEBOOK_CLIENT_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          HOST: ${{secrets.HOST}}
          MYSQL_DB_NAME: ${{secrets.MYSQL_DB_NAME}}
          MYSQL_HOST: ${{secrets.MYSQL_HOST}}
          MYSQL_PORT: ${{secrets.MYSQL_PORT}}
          MYSQL_USER: ${{secrets.MYSQL_USER}}
          NODE_ENV: ${{secrets.NODE_ENV}}
          PORT: ${{secrets.PORT}}
        run: |
          touch .env
          echo APP_KEY="$APP_KEY" >> .env
          echo DB_CONNECTION="$DB_CONNECTION" >> .env
          echo DRIVE_DISK="$DRIVE_DISK" >> .env
          echo FACEBOOK_CLIENT_ID="$FACEBOOK_CLIENT_ID" >> .env
          echo FACEBOOK_CLIENT_SECRET="$FACEBOOK_CLIENT_SECRET" >> .env
          echo GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" >> .env
          echo GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" >> .env
          echo HOST="$HOST" >> .env
          echo MYSQL_DB_NAME="$MYSQL_DB_NAME" >> .env
          echo MYSQL_HOST="$MYSQL_HOST" >> .env
          echo MYSQL_PORT="$MYSQL_PORT" >> .env
          echo MYSQL_USER="$MYSQL_USER" >> .env
          echo NODE_ENV="$NODE_ENV" >> .env
          echo PORT="$PORT" >> .env

      # Run build script
      - name: node
        run: |
          yarn build
      
      # Copy app.yaml into build folder
      - name: gcr.io/cloud-builders/gsutil
        run: |
          cp app.yaml build/app.yaml

      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL_STAGING_NEW }}
          service_account_key: ${{ secrets.GCP_SA_KEY_STAGING_NEW }}
          project_id: ${{ secrets.PROJECT_ID_STAGING_NEW }}
          gae_variables: ${{ secrets.GAE_VARIABLES_STAGING_NEW }}

      # Deploy application     
      - name: Publish app to Google App Engine
        run: |
          # This client-secret.json is converted by GCP_SA_KEY_STAGING_NEW.
          
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL_STAGING_NEW }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID_STAGING_NEW }}


          cd build

          touch .env
          echo APP_KEY="$APP_KEY" >> .env
          echo DB_CONNECTION="$DB_CONNECTION" >> .env
          echo DRIVE_DISK="$DRIVE_DISK" >> .env
          echo FACEBOOK_CLIENT_ID="$FACEBOOK_CLIENT_ID" >> .env
          echo FACEBOOK_CLIENT_SECRET="$FACEBOOK_CLIENT_SECRET" >> .env
          echo GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" >> .env
          echo GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" >> .env
          echo HOST="$HOST" >> .env
          echo MYSQL_DB_NAME="$MYSQL_DB_NAME" >> .env
          echo MYSQL_HOST="$MYSQL_HOST" >> .env
          echo MYSQL_PORT="$MYSQL_PORT" >> .env
          echo MYSQL_USER="$MYSQL_USER" >> .env
          echo NODE_ENV="$NODE_ENV" >> .env
          echo PORT="$PORT" >> .env
          
          yarn install --production
          ls -lah


          gcloud -q app deploy app.yaml
          # Suppose you need a cron task.
          # gcloud -q app deploy cron.yaml
