# This is a basic workflow to help you get started with Actions

name: Staging CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL_STAGING_NEW }}
          service_account_key: ${{ secrets.GCP_SA_KEY_STAGING_NEW }}
          project_id: ${{ secrets.PROJECT_ID_STAGING_NEW }}
          gae_variables: ${{ secrets.GAE_VARIABLES_STAGING_NEW }}

      - name: Publish app to Google App Engine
        run: |
          # This client-secret.json is converted by GCP_SA_KEY_STAGING_NEW.
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL_STAGING_NEW }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID_STAGING_NEW }}
          gcloud -q app deploy dev/app.yaml --promote
          # Suppose you need a cron task.
          # gcloud -q app deploy cron.yaml
